name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "node scripts/safe-prisma-generate.js"
dev = "npx prisma migrate deploy && npm exec react-router dev"
